// RUN: quantum-opt %s -replace-repeated-reads -split-input-file | FileCheck %s
// -lift-qillr-to-quantum -hoist-load-store -eliminate-load-store 
// --debug -mlir-print-ir-after-all

// CHECK-LABEL: @single_read_replaced
func.func public @single_read_replaced() -> (tensor<1xi1>, tensor<1xi1>) {
// CHECK: %[[q:.+]] = "qillr.alloc"() <{size = 1 : i64}> : () -> !qillr.qubit
%0 = "qillr.alloc"() <{size = 1 : i64}> : () -> !qillr.qubit
// CHECK: %[[r:.+]] = "qillr.ralloc"() <{size = 1 : i64}> : () -> !qillr.result
%1 = "qillr.ralloc"() <{size = 1 : i64}> : () -> !qillr.result
// CHECK: "qillr.measure"(%[[q]], %[[r]]) <{inputIndex = [], resultIndex = []}> : (!qillr.qubit, !qillr.result) -> ()
"qillr.measure"(%0, %1) : (!qillr.qubit, !qillr.result) -> ()
// CHECK: %[[m1:.+]] = "qillr.read_measurement"(%[[r]]) <{index = []}> : (!qillr.result) -> tensor<1xi1>
%3 = "qillr.read_measurement"(%1) : (!qillr.result) -> tensor<1xi1>
// CHECK-NOT: "qillr.read_measurement"(%[[r]]) <{index = []}> : (!qillr.result) -> tensor<1xi1>
%4 = "qillr.read_measurement"(%1) : (!qillr.result) -> tensor<1xi1>
"qillr.reset"(%0) : (!qillr.qubit) -> ()
// CHECK: return %[[m1]], %[[m1]]
return %3, %4 : tensor<1xi1>, tensor<1xi1>
}


// -----

// CHECK-LABEL: @multiple_measure_read_replaced
func.func public @multiple_measure_read_replaced() -> (tensor<1xi1>, tensor<1xi1>, tensor<1xi1>) {
// CHECK: %[[q:.+]] = "qillr.alloc"() <{size = 1 : i64}> : () -> !qillr.qubit
%0 = "qillr.alloc"() <{size = 1 : i64}> : () -> !qillr.qubit
// CHECK: %[[r:.+]] = "qillr.ralloc"() <{size = 1 : i64}> : () -> !qillr.result
%1 = "qillr.ralloc"() <{size = 1 : i64}> : () -> !qillr.result
// CHECK: "qillr.measure"(%[[q]], %[[r]]) <{inputIndex = [], resultIndex = []}> : (!qillr.qubit, !qillr.result) -> ()
"qillr.measure"(%0, %1) : (!qillr.qubit, !qillr.result) -> ()
// CHECK: %[[m1:.+]] = "qillr.read_measurement"(%[[r]]) <{index = []}> : (!qillr.result) -> tensor<1xi1>
%3 = "qillr.read_measurement"(%1) : (!qillr.result) -> tensor<1xi1>
// CHECK-NOT: "qillr.read_measurement"(%[[r]]) <{index = []}> : (!qillr.result) -> tensor<1xi1>
%4 = "qillr.read_measurement"(%1) : (!qillr.result) -> tensor<1xi1>
"qillr.reset"(%0) : (!qillr.qubit) -> ()
// CHECK: "qillr.measure"(%[[q]], %[[r]]) <{inputIndex = [], resultIndex = []}> : (!qillr.qubit, !qillr.result) -> ()
"qillr.measure"(%0, %1) : (!qillr.qubit, !qillr.result) -> ()
// CHECK: %[[m2:.+]] = "qillr.read_measurement"(%[[r]]) <{index = []}> : (!qillr.result) -> tensor<1xi1>
%5 = "qillr.read_measurement"(%1) : (!qillr.result) -> tensor<1xi1>
// CHECK: return %[[m1]], %[[m1]], %[[m2]]
return %3, %4, %5 : tensor<1xi1>, tensor<1xi1>, tensor<1xi1>
}


// -----
