//===-- QILLROps.td - Entry point for QILLR bindings -----*- tablegen -*-===//
//                                                                               
// @author  Lars Schütze (lars.schuetze@tu-dresden.de)                                 
//===----------------------------------------------------------------------===// 


#ifndef PYTHON_BINDINGS_QILLR_OPS
#define PYTHON_BINDINGS_QILLR_OPS

include "quantum-mlir/Dialect/QILLR/IR/QILLROps.td"

#endif // PYTHON_BINDINGS_QILLR_OPS
