//===-- QIROps.td - Entry point for QIR bindings -----*- tablegen -*-===//
//                                                                               
// @author  Lars Schütze (lars.schuetze@tu-dresden.de)                                 
//===----------------------------------------------------------------------===// 


#ifndef PYTHON_BINDINGS_QIR_OPS
#define PYTHON_BINDINGS_QIR_OPS

include "quantum-mlir/Dialect/QIR/IR/QIROps.td"

#endif
