//===-- QPUOps.td - Entry point for QPU bindings -----*- tablegen -------*-===//
//                                                                               
// @author  Lars Schütze (lars.schuetze@tu-dresden.de)                                 
//===----------------------------------------------------------------------===// 


#ifndef PYTHON_BINDINGS_QPU_OPS
#define PYTHON_BINDINGS_QPU_OPS

include "quantum-mlir/Dialect/QPU/IR/QPUOps.td"

#endif // PYTHON_BINDINGS_QPU_OPS
