//===-- RVSDGOps.td - Entry point for RVSDG bindings -----*- tablegen ---*-===//
//                                                                               
// @author  Lars Schütze (lars.schuetze@tu-dresden.de)                                 
//===----------------------------------------------------------------------===// 


#ifndef PYTHON_BINDINGS_RVSDG_OPS
#define PYTHON_BINDINGS_RVSDG_OPS

include "quantum-mlir/Dialect/RVSDG/IR/RVSDGOps.td"

#endif // PYTHON_BINDINGS_RVSDG_OPS
