/// Doctest driver main entry point.
///
/// @file
/// @author     Lars Schütze (lars.schuetze@tu-dresden.de)

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

// DO NOT EDIT THIS FILE