//===- Types.td - RVSDG dialect types ------------------*- tablegen -----*-===//
//
// This is the definitions file for the RVSDG dialect types.
//
//===----------------------------------------------------------------------===//

#ifndef RVSDG_TYPES
#define RVSDG_TYPES

include "quantum-mlir/Dialect/RVSDG/IR/RVSDGAttributes.td"
include "mlir/IR/EnumAttr.td"
include "mlir/IR/BuiltinTypeInterfaces.td"


#endif
