//===- Ops.td - RVSDG dialect ops ----------------------*- tablegen -----*-===//
//
// This is the definitions file for the RVSDG dialect ops.
//
//===----------------------------------------------------------------------===//

#ifndef RVSDG_OPS
#define RVSDG_OPS

include "quantum-mlir/Dialect/RVSDG/IR/RVSDGTypes.td"
include "mlir/Interfaces/CastInterfaces.td"
include "mlir/Interfaces/ControlFlowInterfaces.td"
include "mlir/IR/SymbolInterfaces.td"
include "mlir/Interfaces/CallInterfaces.td"
include "mlir/Interfaces/FunctionInterfaces.td"
include "mlir/Interfaces/InferTypeOpInterface.td"
include "mlir/Interfaces/SideEffectInterfaces.td"

//===----------------------------------------------------------------------===//
// RVSDG OP templates
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// RVSDG dialect traits.
//===----------------------------------------------------------------------===//

#endif // RVSDG_OPS
