//===- Attributes.td - QQT dialect attributes --------*- tablegen -*-===//
//
// This is the definitions file for the QQT dialect attributes.
//
//===----------------------------------------------------------------------===//

#ifndef QQT_ATTRIBUTES
#define QQT_ATTRIBUTES

include "mlir/IR/AttrTypeBase.td"
include "mlir/IR/OpBase.td"
include "quantum-mlir/Dialect/QQT/IR/QQTBase.td"

//===----------------------------------------------------------------------===//
// QQT Attributes.
//===----------------------------------------------------------------------===//


#endif // QQT_ATTRIBUTES
