//===- Ops.td - QQT dialect ops ----------------------*- tablegen -*-===//
//
// This is the definitions file for the QQT dialect ops.
//
//===----------------------------------------------------------------------===//

#ifndef QQT_OPS
#define QQT_OPS

include "quantum-mlir/Dialect/QQT/IR/QQTTypes.td"
include "mlir/Interfaces/CastInterfaces.td"
include "mlir/Interfaces/ControlFlowInterfaces.td"
include "mlir/IR/SymbolInterfaces.td"
include "mlir/IR/RegionKindInterface.td"
include "mlir/IR/OpAsmInterface.td"
include "mlir/Interfaces/CallInterfaces.td"
include "mlir/Interfaces/FunctionInterfaces.td"
include "mlir/Interfaces/InferTypeOpInterface.td"
include "mlir/Interfaces/SideEffectInterfaces.td"

//===----------------------------------------------------------------------===//
// QQT Op templates
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// QQT dialect traits.
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// QQT operations.
//===----------------------------------------------------------------------===//


#endif // QQT_OPS
